//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlAl3abProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResWebsite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResWebsite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlAl3abProject.Resources.ResWebsite", typeof(ResWebsite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابجدي من الالف الي الياء.
        /// </summary>
        public static string lbA {
            get {
                return ResourceManager.GetString("lbA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن بنزو.
        /// </summary>
        public static string lbAboutBenzoo {
            get {
                return ResourceManager.GetString("lbAboutBenzoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماذا عنا.
        /// </summary>
        public static string lbAboutUs {
            get {
                return ResourceManager.GetString("lbAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاكونت.
        /// </summary>
        public static string lbAccount {
            get {
                return ResourceManager.GetString("lbAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف ال عربة التسوق.
        /// </summary>
        public static string lbAdd {
            get {
                return ResourceManager.GetString("lbAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان المنزل.
        /// </summary>
        public static string lbAddress {
            get {
                return ResourceManager.GetString("lbAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الدول.
        /// </summary>
        public static string lbAllcountries {
            get {
                return ResourceManager.GetString("lbAllcountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلومات الاساسية.
        /// </summary>
        public static string lbBasicinformation {
            get {
                return ResourceManager.GetString("lbBasicinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل كتاجر او قم بالدخول بالكونت.
        /// </summary>
        public static string lbBecomeourregistereduserorlogin {
            get {
                return ResourceManager.GetString("lbBecomeourregistereduserorlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benzoo هو أحد أكبر متاجر الألعاب وأكثرها ثقة في العالم!.
        /// </summary>
        public static string lbBenzooisone {
            get {
                return ResourceManager.GetString("lbBenzooisone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاعلي مبيعا اي جيفت كارت.
        /// </summary>
        public static string lbBest {
            get {
                return ResourceManager.GetString("lbBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاعلي مبيعا جيفت كارت.
        /// </summary>
        public static string lbBestselling {
            get {
                return ResourceManager.GetString("lbBestselling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدونة.
        /// </summary>
        public static string lbBlog {
            get {
                return ResourceManager.GetString("lbBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث ف التاجات.
        /// </summary>
        public static string lbBrowse {
            get {
                return ResourceManager.GetString("lbBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان العمل.
        /// </summary>
        public static string lbBUSINESSADDRESS {
            get {
                return ResourceManager.GetString("lbBUSINESSADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل العمل.
        /// </summary>
        public static string lbBUSINESSDETAILS {
            get {
                return ResourceManager.GetString("lbBUSINESSDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to للعمل سويا.
        /// </summary>
        public static string lbBusinessDevelopment {
            get {
                return ResourceManager.GetString("lbBusinessDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شراء.
        /// </summary>
        public static string lbBuy {
            get {
                return ResourceManager.GetString("lbBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشتري العاب الكترونية.
        /// </summary>
        public static string lbBuy2 {
            get {
                return ResourceManager.GetString("lbBuy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدفع.
        /// </summary>
        public static string lbCheckout {
            get {
                return ResourceManager.GetString("lbCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string lbcity {
            get {
                return ResourceManager.GetString("lbcity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء فلاتر.
        /// </summary>
        public static string lbClean {
            get {
                return ResourceManager.GetString("lbClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غلق.
        /// </summary>
        public static string lbClose {
            get {
                return ResourceManager.GetString("lbClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......تواصل معنا.
        /// </summary>
        public static string lbContact {
            get {
                return ResourceManager.GetString("lbContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوة القادمة.
        /// </summary>
        public static string lbContinue {
            get {
                return ResourceManager.GetString("lbContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقوق محفوظة رؤية برمجية 2023.
        /// </summary>
        public static string lbCopyright {
            get {
                return ResourceManager.GetString("lbCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدول.
        /// </summary>
        public static string lbCountry {
            get {
                return ResourceManager.GetString("lbCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل اكونت.
        /// </summary>
        public static string lbCreateanaccount {
            get {
                return ResourceManager.GetString("lbCreateanaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاء تيكيت.
        /// </summary>
        public static string lbCreateaticket {
            get {
                return ResourceManager.GetString("lbCreateaticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        public static string lbDashBoard {
            get {
                return ResourceManager.GetString("lbDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string lbDateofbirth {
            get {
                return ResourceManager.GetString("lbDateofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنتجات الالكترونية.
        /// </summary>
        public static string lbDigitalproducts {
            get {
                return ResourceManager.GetString("lbDigitalproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوثائق.
        /// </summary>
        public static string lbDocuments {
            get {
                return ResourceManager.GetString("lbDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string lbEmailaddress {
            get {
                return ResourceManager.GetString("lbEmailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الالعاب الرياضية.
        /// </summary>
        public static string lbEsports {
            get {
                return ResourceManager.GetString("lbEsports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسئلة الشائعة.
        /// </summary>
        public static string lbFaq {
            get {
                return ResourceManager.GetString("lbFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصائص.
        /// </summary>
        public static string lbFeatures {
            get {
                return ResourceManager.GetString("lbFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to املا الفورم.
        /// </summary>
        public static string lbFilloutKYCform {
            get {
                return ResourceManager.GetString("lbFilloutKYCform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فلتر.
        /// </summary>
        public static string lbFilter {
            get {
                return ResourceManager.GetString("lbFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من.
        /// </summary>
        public static string lbfrom {
            get {
                return ResourceManager.GetString("lbfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الكامل.
        /// </summary>
        public static string lbFullname {
            get {
                return ResourceManager.GetString("lbFullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الكامل الانجليزي.
        /// </summary>
        public static string lbFullnameen {
            get {
                return ResourceManager.GetString("lbFullnameen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاعلي الالعاب.
        /// </summary>
        public static string lbGame {
            get {
                return ResourceManager.GetString("lbGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لو عندك سؤال اتصل بنا 24/7.
        /// </summary>
        public static string lbGotQuestion {
            get {
                return ResourceManager.GetString("lbGotQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اهلا.
        /// </summary>
        public static string lbHello {
            get {
                return ResourceManager.GetString("lbHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المساعدة.
        /// </summary>
        public static string lbHelp {
            get {
                return ResourceManager.GetString("lbHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من الاعلي سعرا الي الاقل.
        /// </summary>
        public static string lbhigh {
            get {
                return ResourceManager.GetString("lbhigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيف تقوم الشراء.
        /// </summary>
        public static string lbHowtobuy {
            get {
                return ResourceManager.GetString("lbHowtobuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيف ابدا.
        /// </summary>
        public static string lbHowtostart {
            get {
                return ResourceManager.GetString("lbHowtostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زيادة وصول منتجاتك مع Eneba يمكنك بيع المزيد..
        /// </summary>
        public static string lbIncrease {
            get {
                return ResourceManager.GetString("lbIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاكل.
        /// </summary>
        public static string lbISSUES {
            get {
                return ResourceManager.GetString("lbISSUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحديث.
        /// </summary>
        public static string lbLatest {
            get {
                return ResourceManager.GetString("lbLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to للشؤون القانونية.
        /// </summary>
        public static string lbLegalDepartment {
            get {
                return ResourceManager.GetString("lbLegalDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل اكتر.
        /// </summary>
        public static string lbLoad {
            get {
                return ResourceManager.GetString("lbLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدخول.
        /// </summary>
        public static string lbLogIn {
            get {
                return ResourceManager.GetString("lbLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من الاقل سعرا الي الاعلي.
        /// </summary>
        public static string lbLow {
            get {
                return ResourceManager.GetString("lbLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الي.
        /// </summary>
        public static string lbmax {
            get {
                return ResourceManager.GetString("lbmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من.
        /// </summary>
        public static string lbminu {
            get {
                return ResourceManager.GetString("lbminu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من الاحدث الي الاقدم.
        /// </summary>
        public static string lbNewest {
            get {
                return ResourceManager.GetString("lbNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار.
        /// </summary>
        public static string lbNews {
            get {
                return ResourceManager.GetString("lbNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل العرض.
        /// </summary>
        public static string lbOfferDetails {
            get {
                return ResourceManager.GetString("lbOfferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من الاقدم الي الاحدث.
        /// </summary>
        public static string lbOldest {
            get {
                return ResourceManager.GetString("lbOldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام التشغيل.
        /// </summary>
        public static string lbOperating {
            get {
                return ResourceManager.GetString("lbOperating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئات.
        /// </summary>
        public static string lbOurCategories {
            get {
                return ResourceManager.GetString("lbOurCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الشخصية.
        /// </summary>
        public static string lbPERSONALDETAILS {
            get {
                return ResourceManager.GetString("lbPERSONALDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التليفون.
        /// </summary>
        public static string lbPhonenumber {
            get {
                return ResourceManager.GetString("lbPhonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البلاتفورم.
        /// </summary>
        public static string lbPlatforms {
            get {
                return ResourceManager.GetString("lbPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك.
        /// </summary>
        public static string lbPlease {
            get {
                return ResourceManager.GetString("lbPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشهور.
        /// </summary>
        public static string lbPopular {
            get {
                return ResourceManager.GetString("lbPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        public static string lbPrice {
            get {
                return ResourceManager.GetString("lbPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم اللعبة.
        /// </summary>
        public static string lbProduct {
            get {
                return ResourceManager.GetString("lbProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشراء؟.
        /// </summary>
        public static string lbPURCHASE {
            get {
                return ResourceManager.GetString("lbPURCHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجمالي عدد التقييمات.
        /// </summary>
        public static string lbratings {
            get {
                return ResourceManager.GetString("lbratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوصي به.
        /// </summary>
        public static string lbRecommended {
            get {
                return ResourceManager.GetString("lbRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البقعة الجغرافية.
        /// </summary>
        public static string lbRegions {
            get {
                return ResourceManager.GetString("lbRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم جديد.
        /// </summary>
        public static string lbRegister {
            get {
                return ResourceManager.GetString("lbRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الالعاب.
        /// </summary>
        public static string lbResults {
            get {
                return ResourceManager.GetString("lbResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احفظ ما سجلت وكمل لاحقا.
        /// </summary>
        public static string lbSaveforlater {
            get {
                return ResourceManager.GetString("lbSaveforlater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابحث بالبلاتفورم.
        /// </summary>
        public static string lbSearchbyplatform {
            get {
                return ResourceManager.GetString("lbSearchbyplatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابحث باسم اللعبة.
        /// </summary>
        public static string lbSearchbyproduct {
            get {
                return ResourceManager.GetString("lbSearchbyproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابحث بالبقعة الجغرافية.
        /// </summary>
        public static string lbSearchbyregion {
            get {
                return ResourceManager.GetString("lbSearchbyregion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابحث عن الاسئلة الشائعة.
        /// </summary>
        public static string lbSearchFaq {
            get {
                return ResourceManager.GetString("lbSearchFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string lbSearchIn {
            get {
                return ResourceManager.GetString("lbSearchIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم ببيع لعب اكثر.
        /// </summary>
        public static string lbSellmoregames {
            get {
                return ResourceManager.GetString("lbSellmoregames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم بالبيع عل بنزو.
        /// </summary>
        public static string lbSellonBenzoo {
            get {
                return ResourceManager.GetString("lbSellonBenzoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهز بيانات الدفع.
        /// </summary>
        public static string lbSetupyourpayments {
            get {
                return ResourceManager.GetString("lbSetupyourpayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلة التسوق.
        /// </summary>
        public static string lbShoppingCart {
            get {
                return ResourceManager.GetString("lbShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وسائل التواصل الاجتماعي.
        /// </summary>
        public static string lbsocial {
            get {
                return ResourceManager.GetString("lbsocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشتغل كتاجر.
        /// </summary>
        public static string lbStart {
            get {
                return ResourceManager.GetString("lbStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل لديك اسئلة اخري؟.
        /// </summary>
        public static string lbStill {
            get {
                return ResourceManager.GetString("lbStill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاجمالي.
        /// </summary>
        public static string lbSubtotal {
            get {
                return ResourceManager.GetString("lbSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to للحصول عل وظيفة لدينا.
        /// </summary>
        public static string lbTalentteam {
            get {
                return ResourceManager.GetString("lbTalentteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التعريف الضريبي.
        /// </summary>
        public static string lbTaxidentificationnumber {
            get {
                return ResourceManager.GetString("lbTaxidentificationnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افضل طريقة للحل هو.
        /// </summary>
        public static string lbThebestway {
            get {
                return ResourceManager.GetString("lbThebestway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لمعرفة المزيد عن الخدمة..
        /// </summary>
        public static string lbtolearn {
            get {
                return ResourceManager.GetString("lbtolearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم التجاري.
        /// </summary>
        public static string lbTradename {
            get {
                return ResourceManager.GetString("lbTradename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلومات التجارية.
        /// </summary>
        public static string lbTradeReferences {
            get {
                return ResourceManager.GetString("lbTradeReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التريند.
        /// </summary>
        public static string lbTrending {
            get {
                return ResourceManager.GetString("lbTrending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع اللعبة.
        /// </summary>
        public static string lbType {
            get {
                return ResourceManager.GetString("lbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الالعاب الحديثة.
        /// </summary>
        public static string lbUpcoming {
            get {
                return ResourceManager.GetString("lbUpcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الضريبة المضافة.
        /// </summary>
        public static string lbVATnumber {
            get {
                return ResourceManager.GetString("lbVATnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الذهاب ال عربة التسوق.
        /// </summary>
        public static string lbViewCart {
            get {
                return ResourceManager.GetString("lbViewCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نستخدم بوابات دفع امنة.
        /// </summary>
        public static string lbWe {
            get {
                return ResourceManager.GetString("lbWe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع الالكتروني.
        /// </summary>
        public static string lbWebsite {
            get {
                return ResourceManager.GetString("lbWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيف استطيع ان اساعدك.
        /// </summary>
        public static string lbWhatdo {
            get {
                return ResourceManager.GetString("lbWhatdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابجدي من الياء الي الالف.
        /// </summary>
        public static string lbZ {
            get {
                return ResourceManager.GetString("lbZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز البريدي.
        /// </summary>
        public static string lbZIPCODE {
            get {
                return ResourceManager.GetString("lbZIPCODE", resourceCulture);
            }
        }
    }
}
